baseURL = "https://terraversal-comics.github.io/terraversal.comics/"
languageCode = "en-us"
title = "Terraversal Comics"
theme = "ananke" # ✔️ Your confirmed theme name
disableKinds = ["taxonomy", "term"]

[params]
  description = "Recent content on Terraversal Comics"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]

# 💥 The actual fix to stop the YAML block showing in the RSS feed:
[mediaTypes]
  [mediaTypes."application/rss"]
    # Tell Hugo to use the plain text version of the summary
    suffix = "+xml"

[outputFormats.RSS]
  mediaType = "application/rss"
  # This line specifically tells Hugo to use a custom template for the description
  # which usually defaults to .Summary.Plain or .Content.
  # By default, Hugo uses the internal template, but this is a failsafe.
  baseName = "index"
