baseURL = "https://terraversal-comics.github.io/terraversal.comics/"
languageCode = "en-us"
title = "Terraversal Comics"
theme = "ananke"

[params]
  description = "Recent content on Terraversal Comics"

[outputs]
  home = ["HTML", "RSS"]
